---
- name: make sure apache is installed
  package: >
    name=apache2
    state=present

- name: proxy module
  apache2_module: >
    state=present
    name={{ item }}
  with_items:
    - proxy
    - proxy_http
    - ssl

- name: disable default site
  command: a2dissite 000-default

- name: add site
  template: >
    src=ssl-template.conf.j2
    dest=/etc/apache2/sites-available/{{available.sitename}}.conf
    mode=644
    owner=root
    group=root

- name: enable main site
  command: a2ensite "{{available.sitename}}"

- name: restart apache
  service: >
    name=apache2
    state=restarted
